layout_spectrum: 0.2624614031519741
typography_spectrum: 0.15537632396444678
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.30298986518755555
  lightness: 0.7453787766862661
  saturation: 0.223217781400308
  rhythmicContrast: 0.6014339178800583
name: Connor Donohue
favicon: null
navigation:
  - name: YouTube
    url: 'https://www.youtube.com/playlist?list=PLWFNavm4ziF0Vw5yvuQ0F2jc2LDnmWkt9'
    type: external
  - name: NCSA Recruiting Profile
    url: 'http://recruit-match.ncsasports.org/clientrms/athletes/2741360?'
    type: external
title: Working Toward the Dream of Playing Baseball at the Next Level
description: Getting Better and Smiling EVERY Day and Step of the Way.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
