layout_spectrum: 0.41028960165567696
typography_spectrum: 0.36504609417170286
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.7121513970196247
  lightness: 0.03771267784759402
  saturation: 0.007487233029678464
  rhythmicContrast: 0.8172052446752787
name: Connor Donohue
favicon: null
navigation:
  - name: YouTube
    url: 'https://www.youtube.com/playlist?list=PLWFNavm4ziF0Vw5yvuQ0F2jc2LDnmWkt9'
    type: external
  - name: NCSA Recruiting Profile
    url: 'http://recruit-match.ncsasports.org/clientrms/athletes/2741360?'
    type: external
title: Working Toward the Dream of Playing Baseball at the Next Level
description: Getting Better EVERY Day.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
