typography_spectrum: 0.85445
color:
  brandColors: []
  brandStrength: 0.3693894527386874
  lightness: 0.08252875995822251
  saturation: 0.49448166019283235
  rhythmicContrast: 0.6417466013226658
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Connor Donohue
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: YouTube
    url: 'https://www.youtube.com/playlist?list=PLWFNavm4ziF0Vw5yvuQ0F2jc2LDnmWkt9'
    type: external
favicon: null
title: Working Toward the Dream of Playing Baseball at the Next Level
description: Getting Better EVERY Day.
purpose: []
