name: Connor Donohue
favicon: null
layout_spectrum: 0.2456
typography_spectrum: 0.85445
navigation:
  - name: YouTube
    url: 'https://www.youtube.com/playlist?list=PLWFNavm4ziF0Vw5yvuQ0F2jc2LDnmWkt9'
    type: external
  - name: NCSA Recruiting Profile
    url: 'http://recruit-match.ncsasports.org/clientrms/athletes/2741360?'
    type: external
title: Working Toward the Dream of Playing Baseball at the Next Level
description: Getting Better EVERY Day.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3693894527386874
  lightness: 0.08252875995822251
  saturation: 0.49448166019283235
  rhythmicContrast: 0.6417466013226658
purpose: []
